/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUICandidatos.java
 *
 * Created on 12/08/2011, 03:59:43
 */
package jurna.visao.gui;

import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jurna.excecao.JUrnaException;
import jurna.modelo.dominio.Candidato;
import jurna.modelo.dominio.constante.Constante;
import jurna.visao.ouvinte.OuvinteDeGUICadastroDeCandidato;

/**
 *
 * @author Gleydson_2
 */
public class GUICandidatos extends javax.swing.JInternalFrame {

    /** Creates new form GUICandidatos */
    public GUICandidatos() {
        initComponents();
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 6, (d.height
                - this.getSize().height) / 6);
    }

    private void abrirGUICadastroDeCandidato(Candidato candidato) throws JUrnaException {
        if ((guiCadastroDeCandidatos == null) || (!guiCadastroDeCandidatos.isVisible())) {
            guiCadastroDeCandidatos = new GUICadastroDeCandidatos();
            OuvinteDeGUICadastroDeCandidato ouvinte = new OuvinteDeGUICadastroDeCandidato(guiCadastroDeCandidatos);
            this.getParent().add(guiCadastroDeCandidatos);
            guiCadastroDeCandidatos.setPosicao();
            guiCadastroDeCandidatos.setVisible(true);

            guiCadastroDeCandidatos.setCandidato(candidato);
        }
        try {
            guiCadastroDeCandidatos.setSelected(true);
        } catch (PropertyVetoException exc) {
            StringBuffer mensagem = new StringBuffer();
            mensagem.append("Não foi possível selecionar a janela de cadastro de candidato!");
            mensagem.append("\nMotivo: " + exc.getMessage());
            GUIMensagem.exibirMensagem(mensagem.toString(), "JUrna - Cadastro de candidato", true);
        }
    }

    public void exibirCandidatos(List candidatos) {
        this.candidatos = candidatos;

        DefaultTableModel model = (DefaultTableModel) tCandidatos.getModel();
        this.removerLinhasDaTabela(model);

        Iterator resultado = candidatos.iterator();

        while (resultado.hasNext()) {
            Candidato candidato = (Candidato) resultado.next();
            String numero = ""+candidato.getNumero();
            String nome = candidato.getNome();
            String partido = candidato.getPartido();

            Object[] linha = {numero, nome, partido};

            model.addRow(linha);
        }
    }

    private void removerLinhasDaTabela(DefaultTableModel model) {
        while (model.getRowCount() > 0) {
            int ultimaLinha = model.getRowCount() - 1;
            model.removeRow(ultimaLinha);
        }
    }

    public String getNome() {
        return tfNome.getText().trim();
    }

    public void bPesquisarCandidatoAddActionListener(ActionListener ouvinte) {
        bPesquisar.addActionListener(ouvinte);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tCandidatos = new javax.swing.JTable();
        bNovoCandidato = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bExcluir = new javax.swing.JButton();
        pPesquisar = new javax.swing.JPanel();
        lNumero = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        bPesquisar = new javax.swing.JButton();

        setClosable(true);
        setTitle("JUrna -  Candidatos");

        tCandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Nome", "Partido"
            }
        ));
        tCandidatos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tCandidatos);

        bNovoCandidato.setText("Novo candidato");
        bNovoCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovoCandidatoActionPerformed(evt);
            }
        });

        jButton1.setText("Alterar");

        bExcluir.setText("Excluir");

        pPesquisar.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar candidato"));

        lNumero.setText("Numero");

        bPesquisar.setText("Pesquisar");

        javax.swing.GroupLayout pPesquisarLayout = new javax.swing.GroupLayout(pPesquisar);
        pPesquisar.setLayout(pPesquisarLayout);
        pPesquisarLayout.setHorizontalGroup(
            pPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPesquisarLayout.createSequentialGroup()
                .addGroup(pPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNumero)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPesquisar))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        pPesquisarLayout.setVerticalGroup(
            pPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPesquisarLayout.createSequentialGroup()
                .addComponent(lNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bPesquisar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addComponent(bNovoCandidato, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(bExcluir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bNovoCandidato)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bExcluir)
                        .addComponent(jButton1))
                    .addComponent(pPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNovoCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovoCandidatoActionPerformed
        Candidato candidato = new Candidato();
        candidato.setCodigo(Constante.NOVO);
        try {
            this.abrirGUICadastroDeCandidato(candidato);
        } catch (JUrnaException ex) {
            Logger.getLogger(GUICandidatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bNovoCandidatoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExcluir;
    private javax.swing.JButton bNovoCandidato;
    private javax.swing.JButton bPesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lNumero;
    private javax.swing.JPanel pPesquisar;
    private javax.swing.JTable tCandidatos;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
    private GUICadastroDeCandidatos guiCadastroDeCandidatos;
    private List candidatos;
}
