/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIPrincipal.java
 *
 * Created on 05/08/2011, 01:28:46
 */
package jurna.visao.gui;

import jurna.visao.gui.GUISobre;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import javax.swing.JFrame;
import jurna.visao.ouvinte.OuvinteDeGUICandidatos;
import jurna.visao.ouvinte.OuvinteDeGUIUrna;

/**
 *
 * @author Gleydson_2
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /** Creates new form GUIPrincipal */
    public GUIPrincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        bVotar.setLocation(450, 80);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        bVotar = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        itemDeMenuCadCandidato = new javax.swing.JMenuItem();
        itemDeMenuCadEleitor = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        itemDeMenuRelatorioDeVotacao = new javax.swing.JMenuItem();
        itemDeMenuRelatorioDeEleitores = new javax.swing.JMenuItem();
        itemDeMenuRelatorioDeCandidatos = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        itemDeMenuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaUrna");

        bVotar.setBackground(new java.awt.Color(51, 204, 0));
        bVotar.setText("VOTAR");
        bVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVotarActionPerformed(evt);
            }
        });
        bVotar.setBounds(140, 30, 130, 30);
        desktopPane.add(bVotar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        menuCadastro.setMnemonic('e');
        menuCadastro.setText("Cadastro");

        itemDeMenuCadCandidato.setMnemonic('t');
        itemDeMenuCadCandidato.setText("Candidato");
        itemDeMenuCadCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuCadCandidatoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemDeMenuCadCandidato);

        itemDeMenuCadEleitor.setMnemonic('y');
        itemDeMenuCadEleitor.setText("Eleitor");
        menuCadastro.add(itemDeMenuCadEleitor);

        menuBar.add(menuCadastro);

        menuRelatorio.setMnemonic('e');
        menuRelatorio.setText("Relatório");

        itemDeMenuRelatorioDeVotacao.setMnemonic('t');
        itemDeMenuRelatorioDeVotacao.setText("Votação");
        menuRelatorio.add(itemDeMenuRelatorioDeVotacao);

        itemDeMenuRelatorioDeEleitores.setMnemonic('y');
        itemDeMenuRelatorioDeEleitores.setText("Eleitores");
        menuRelatorio.add(itemDeMenuRelatorioDeEleitores);

        itemDeMenuRelatorioDeCandidatos.setText("Candidatos");
        menuRelatorio.add(itemDeMenuRelatorioDeCandidatos);

        menuBar.add(menuRelatorio);

        menuAjuda.setMnemonic('h');
        menuAjuda.setText("Ajuda");

        itemDeMenuSobre.setMnemonic('a');
        itemDeMenuSobre.setText("Sobre");
        itemDeMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeMenuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(itemDeMenuSobre);

        menuBar.add(menuAjuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemDeMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuSobreActionPerformed
        if ((guiSobre == null) || (!guiSobre.isVisible())) {
            guiSobre = new GUISobre();
            desktopPane.add(guiSobre);
            guiSobre.setPosicao();
            guiSobre.setVisible(true);
        }
    }//GEN-LAST:event_itemDeMenuSobreActionPerformed

    private void itemDeMenuCadCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeMenuCadCandidatoActionPerformed
        if ((guiCandidatos == null) || (!guiCandidatos.isVisible())) {
            guiCandidatos = new GUICandidatos();
            desktopPane.add(guiCandidatos);
            guiCandidatos.setPosicao();
            guiCandidatos.setVisible(true);
            OuvinteDeGUICandidatos ouvinte = new OuvinteDeGUICandidatos(guiCandidatos);
        }

        try {
            guiCandidatos.setSelected(true);
        } catch (PropertyVetoException exc) {
            StringBuffer mensagem = new StringBuffer();
            mensagem.append("Não foi possível selecionar a janela!");
            mensagem.append("\nMotivo: " + exc.getMessage());
            GUIMensagem.exibirMensagem(mensagem.toString(), "JUrna - Candidatos", true);
        }
    }//GEN-LAST:event_itemDeMenuCadCandidatoActionPerformed

    private void bVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVotarActionPerformed
        if ((guiUrna == null) || (!guiUrna.isVisible())) {
            guiUrna = new GUIUrna();
            OuvinteDeGUIUrna ouvinte = new OuvinteDeGUIUrna(guiUrna);           
            desktopPane.add(guiUrna);
            guiUrna.setPosicao();
            guiUrna.setVisible(true);
        }
    }//GEN-LAST:event_bVotarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bVotar;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem itemDeMenuCadCandidato;
    private javax.swing.JMenuItem itemDeMenuCadEleitor;
    private javax.swing.JMenuItem itemDeMenuRelatorioDeCandidatos;
    private javax.swing.JMenuItem itemDeMenuRelatorioDeEleitores;
    private javax.swing.JMenuItem itemDeMenuRelatorioDeVotacao;
    private javax.swing.JMenuItem itemDeMenuSobre;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuRelatorio;
    // End of variables declaration//GEN-END:variables
    private GUISobre guiSobre;
    private GUICandidatos guiCandidatos;
    private GUIUrna guiUrna;
}
